version: 2
jobs:
  build:
    working_directory: ~/api
    docker:
      - image: microsoft/dotnet:2.0-sdk-jessie
      - image: postgres
	environment:
	- POSTGRES_PASSWORD=postgres
    environment:
      - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet build
      - run: dotnet test BooksEditor.DataAccess.Tests
